### ISSUE TITLE
Incompatibility issues with sed commands on Mac vs. Linux

### ISSUE THREAD

**Issue by fordmadox** [YaleArchivesSpace/YAML#3]
@mark-cooper :  one of our recent updated to this YAML plugin ran into issues due to some incompatibility issues when running the pluginify.sh script on a Mac (e.g. these extra "en" keys crept in, https://github.com/YaleArchivesSpace/YAML/commit/787fd83d4ce108561ed76a585c49090bdfb84752#diff-08a71bd50434a4871c86aa8e6e2d82d2L1986, which have since been removed).  That must mean that the pluginify script is not run on your end at time that this plugin is pulled in, right? 

To make the sed parts compatible across platforms, I *think* that would require changing how the in-place commands work, likely creating backup files and then deleting them afterwards.... as well as changing how the newline is added once the first "en:" key is re-added (or just not removing that one instance of "en" in the first place)...?

Do you think it would it be better to:

1. Change things so that the pluginify.sh script is run at the same time this particular plugin is pulled in, thereby negating the need to ensure that the script also works on a Mac?
2. Update the pluginify.sh script to work on both Mac and Linux?
3. Scrap the script altogether, and just leave the "frontend" directory in this plugin.... as well as adding the "public" directory of YML files which we currently have elsewhere (but we didn't add here since it wasn't part of the pluginify script).

Happy to proceed with whichever option that you think would be best.   If option 1, then I don't think that we need to do anything on our end here at Yale.  If option 2 or 3, then I should be able to make those updates on my own (I *think* it should be fine to use 'sed' on both platforms, but it might be easier to use something else).

**Comment by mark-cooper** [comment]
"That must mean that the pluginify script is not run on your end at time that this plugin is pulled in, right?"

Correct, on our end we are just enabling plugins. We support configuration (AppConfig) and initialization (for Gems). But no supporting scripts or anything like that are run.

Reviewing the options I'm not very keen on 1. I think when we pull the plugin the assumption that it is ready to use is a good (and consistent) one, and it means it's possible for you (or anyone) to test it locally in the exact same state that we receive it.

I'm not sure I have a recommendation on 2 vs. 3. If you go with 3. you probably want to make sure it's very clear which plugin the entries belong to. The plugin folders have that distinction built in and also make it possible at any time to switch to putting the locale updates back with the individual plugin repos (option 4.).

**Comment by fordmadox** [comment]
Thanks!  I'm guessing that we didn't go with option 4 originally since we didn't have control over (or forks of) all of the plugins that we were using originally, so we couldn't just update YML files as needed.  I think it makes sense to keep that distinction now that you mention it

Given all that, I say that we pursue option 2 on our end.  And in the meantime we just won't run that script on a Mac.

**Comment by mark-cooper** [comment]
:+1:

**Comment by triplingual** [comment]
We do not use this plugin any longer, and having checked with @mark-cooper as well, we are going to archive it. For tidiness, I'm going to close this issue as `wontfix`.
